# Generated by Django 5.1.4 on 2024-12-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='number_of_employees',
        ),
    ]
