# Generated by Django 5.1.4 on 2024-12-12 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_number_of_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 12, 0, 57, 9, 774972, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
