# Generated by Django 5.1.4 on 2024-12-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_of_departments', models.PositiveIntegerField(default=0, editable=False)),
                ('number_of_employees', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
