# Generated by Django 5.1.4 on 2024-12-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_departments',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number_of_employees',
        ),
    ]
