# Generated by Django 5.1.4 on 2024-12-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_number_of_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='not_provided'),
            preserve_default=False,
        ),
    ]
